version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory:
  files:
    - "**/*"

# cd haha && npm install/run build if in "haha" folder